### PR TITLE
Zebra pull request

### PR DESCRIPTION
**Pull request by AdamAudio7X**
This is a Zebra pull request

### CODE REVIEW

**Comment by AdamAudio7Xemp01** [comment]
do u want to add Zebra3?

**Comment by AdamAudio7X** [comment]
I just did.

**Comment by AdamAudio7Xemp01** [comment]
Fix Z3

**Comment by AdamAudio7Xemp01** [comment]
I'm gonna commit

**Comment by AdamAudio7X** [comment]
no problemo boss

**Pull request merged**
